### ISSUE TITLE
Re-license under Apache 2.

### ISSUE THREAD

**Issue by apetro** [kdjohnson/courses-ada#23]
Hypothesis: this source code may someday want to be an actual Apereo sub-project.

That transition is going to be easier if it's Apache2 licensed. Easiest time to make that licensing change is now, while you're still able to identify and secure unambiguous permission from all the contributors.

**Comment by kdjohnson** [comment]
To help with this being apart of the Apereo ecosystem if that should ever come to pass. I will change the license of this project to be Apache 2.0
